package springdemo.mvc;

import java.util.LinkedHashMap;

// this class is accessed from model attribute: student used in student-form.jsp
public class Student {
	
	private String firstName;
	private String lastName;
	private String country;
	private LinkedHashMap<String, String> countryOptions;
	private String favoriteLanguage;
	private String operatingSystems;
	
	public Student() {
		
		countryOptions = new LinkedHashMap<>();
		countryOptions.put("IN", "India");
		countryOptions.put("CN", "China");
		countryOptions.put("SL", "Srilanka");
		countryOptions.put("SPA", "Spain");
		
	}
	
	
	// generated by eclipse's getters and setters method
	
	public String getFirstName() {
		return firstName;
	}
	
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
	
	public String getLastName() {
		return lastName;
	}
	
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}
	
	public String getCountry() {
		return country;
	}
	
	public void setCountry(String country) {
		this.country = country;
	}


	public LinkedHashMap<String, String> getCountryOptions() {
		return countryOptions;
	}


	public String getFavoriteLanguage() {
		return favoriteLanguage;
	}


	public void setFavoriteLanguage(String favoriteLanguage) {
		this.favoriteLanguage = favoriteLanguage;
	}
	
	public String getOperatingSystems() {
		return operatingSystems;
	}


	public void setOperatingSystems(String operatingSystems) {
		this.operatingSystems = operatingSystems;
	}

	
}
